sonar.projectKey=yuribodo_zksettle
sonar.organization=yuribodo


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=zksettle
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Exclude non-production code from analysis
sonar.exclusions=\
  scripts/**/*,\
  circuits/**/*,\
  docs/**/*,\
  backend/migrations/**/*,\
  **/target/**/*,\
  **/*.lock

# Exclude CLI scripts from coverage analysis
sonar.coverage.exclusions=scripts/**/*
