[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = true


[programs.devnet]
zksettle = "2HexcvYg6zvQo6kf1ompmvG78GUKMTW292kp1wDdKzFk"
stablecoin = "8UCELgX3D64aWPJcJre7AtuoSre5eWjHdAFsRUkeqCMe"

[programs.localnet]
zksettle = "2HexcvYg6zvQo6kf1ompmvG78GUKMTW292kp1wDdKzFk"
stablecoin = "8UCELgX3D64aWPJcJre7AtuoSre5eWjHdAFsRUkeqCMe"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
